### ISSUE TITLE
Integrate Gradio for UI 

### ISSUE THREAD

**Issue by kaybrian** [pycon-rwanda/Endangered-Species-Tracker#3]
Create a basic Gradio interface that allows users to input a species name and displays its information (population, habitat, conservation status).

**Comment by JohananOppongAmoateng** [comment]
@kaybrian assign this to me

**Comment by JohananOppongAmoateng** [comment]
@kaybrian I think this issue should be closed seems it's been worked on

**Comment by kaybrian** [comment]
yes, this is done and I have just confirmed that, I guess its ok for us to close it.
