### ISSUE TITLE
Display Data in a User-Friendly Format

### ISSUE THREAD

**Issue by kaybrian** [pycon-rwanda/Endangered-Species-Tracker#5]
Format the API response data to display in a more user-friendly manner in the Gradio interface (e.g., using cards or tables).

**Comment by roshankraveendrababu** [comment]
can you please assign me this issue under the hacktoberfest-2024 banner. i am entry level aspiring data scientist and i will complete this task to the best of my abilities diligently picking up new concepts along the way and make this repository an roaring success . please consider my application

**Comment by kaybrian** [comment]
Hello @roshankraveendrababu i think you have been able to implement this right ?

**Comment by roshankraveendrababu** [comment]
> Hello @roshankraveendrababu i think you have been able to implement this right ?

sure bruh! will do it .consider it done

**Comment by kaybrian** [comment]
Nice I love this.
